dist: trusty

language: d

d:
  - dmd
  #- gdc
  - ldc

env:
  - VIBE_VERSION='--version=0.7.31'
  - VIBE_VERSION='--version=0.8.0'
  - VIBE_VERSION=''

addons:
  postgresql: 9.6

services: postgresql

before_install:
  - dub fetch dscanner
  - dub fetch doveralls

before_script:
  - dub fetch vibe-d $VIBE_VERSION
  - psql -c 'create database "dpq2-test"' -U postgres

script: ./.test.sh "dbname=postgres"

after_success:
  - rm -f .\.-*.lst
  - if [ ${DC} = "dmd" ]; then dub run doveralls; fi
  - if [ ${DC} = "dmd" ]; then bash <(curl -s https://codecov.io/bash); fi
